version: '3.8'

services:
  db:
    image: mysql:latest 
    restart: always
    container_name: Employees_control
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_USER}
    ports:
      - '3306:3306'
    expose:
      - '3306' 
    volumes:
      - ./mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - '8080:80'
    links:
      - db
    depends_on:
      - db

volumes:
  mysql-data:
